[package]
name = "cheess"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3"
interprocess = "2.2"
serde = { version = "1", features = ["derive"] }
serde_repr = "0.1"
serde_json = "1"
serde-jsonlines = "0.6"